import { compat, types as T } from "../deps.ts";

export const getConfig: T.ExpectedExports.getConfig = compat.getConfig({
  "tor-address": {
    "name": "Tor Address",
    "description": "The Tor address for the main interface.",
    "type": "pointer",
    "subtype": "package",
    "package-id": "btc-rpc-proxy",
    "target": "tor-address",
    "interface": "main",
  },
  "bitcoind-user": {
    "type": "pointer",
    "name": "RPC Username",
    "description": "The username for the RPC user for Bitcoin Core",
    "subtype": "package",
    "package-id": "bitcoind",
    "target": "config",
    "selector": "$.rpc.username",
    "multi": false,
  },
  "bitcoind-password": {
    "type": "pointer",
    "name": "RPC Password",
    "description": "The password for the RPC user for Bitcoin Core",
    "subtype": "package",
    "package-id": "bitcoind",
    "target": "config",
    "selector": "$.rpc.password",
    "multi": false,
  },
  "users": {
    "type": "list",
    "name": "RPC Users",
    "description": "Credentials and permissions for each RPC User",
    "range": "[0,*)",
    "subtype": "object",
    "spec": {
      "unique-by": "name",
      "display-as": "{{name}}",
      "spec": {
        "name": {
          "type": "string",
          "name": "Username",
          "description": "The username for the RPC User",
          "nullable": false,
          "default": "bitcoin",
          "copyable": true,
        },
        "password": {
          "type": "string",
          "name": "Password",
          "description": "The password for the RPC User",
          "nullable": false,
          "copyable": true,
          "masked": true,
          "default": {
            "charset": "a-z,A-Z,0-9",
            "len": 22,
          },
        },
        "allowed-calls": {
          "type": "list",
          "name": "Allowed Calls",
          "description":
            "The list of all RPC methods this user is allowed to make",
          "subtype": "enum",
          "range": "[0, *)",
          "spec": {
            "value-names": {},
            "values": [
              "abandontransaction",
              "abortrescan",
              "addconnection",
              "addmultisigaddress",
              "addnode",
              "addpeeraddress",
              "analyzepsbt",
              "backupwallet",
              "bumpfee",
              "clearbanned",
              "combinepsbt",
              "combinerawtransaction",
              "converttopsbt",
              "createmultisig",
              "createpsbt",
              "createrawtransaction",
              "createwallet",
              "decodepsbt",
              "decoderawtransaction",
              "decodescript",
              "deriveaddresses",
              "disconnectnode",
              "dumpprivkey",
              "dumptxoutset",
              "dumpwallet",
              "echo",
              "echoipc",
              "echojson",
              "encryptwallet",
              "estimaterawfee",
              "estimatesmartfee",
              "finalizepsbt",
              "fundrawtransaction",
              "generate",
              "generateblock",
              "generatetoaddress",
              "generatetodescriptor",
              "getaddednodeinfo",
              "getaddressesbylabel",
              "getaddressinfo",
              "getbalance",
              "getbalances",
              "getbestblockhash",
              "getblock",
              "getblockchaininfo",
              "getblockcount",
              "getblockfilter",
              "getblockhash",
              "getblockheader",
              "getblockfrompeer",
              "getblockstats",
              "getblocktemplate",
              "getchaintips",
              "getchaintxstats",
              "getconnectioncount",
              "getdeploymentinfo",
              "getdescriptorinfo",
              "getdifficulty",
              "getindexinfo",
              "getinfo",
              "getmemoryinfo",
              "getmempoolancestors",
              "getmempooldescendants",
              "getmempoolentry",
              "getmempoolinfo",
              "getmininginfo",
              "getnettotals",
              "getnetworkhashps",
              "getnetworkinfo",
              "getnewaddress",
              "getnodeaddresses",
              "getpeerinfo",
              "getrawchangeaddress",
              "getrawmempool",
              "getrawtransaction",
              "getreceivedbyaddress",
              "getreceivedbylabel",
              "getrpcinfo",
              "gettransaction",
              "gettxout",
              "gettxoutproof",
              "gettxoutsetinfo",
              "gettxspendingprevout",
              "getunconfirmedbalance",
              "getwalletinfo",
              "getzmqnotifications",
              "help",
              "importaddress",
              "importdescriptors",
              "importmulti",
              "importprivkey",
              "importprunedfunds",
              "importpubkey",
              "importwallet",
              "invalidateblock",
              "joinpsbts",
              "keypoolrefill",
              "listaddressgroupings",
              "listbanned",
              "listlabels",
              "listlockunspent",
              "listreceivedbyaddress",
              "listreceivedbylabel",
              "listsinceblock",
              "listtransactions",
              "listunspent",
              "listwalletdir",
              "listwallets",
              "loadwallet",
              "lockunspent",
              "logging",
              "mockscheduler",
              "ping",
              "preciousblock",
              "prioritisetransaction",
              "pruneblockchain",
              "psbtbumpfee",
              "reconsiderblock",
              "removeprunedfunds",
              "rescanblockchain",
              "savemempool",
              "scantxoutset",
              "send",
              "sendall",
              "sendmany",
              "sendrawtransaction",
              "sendtoaddress",
              "setban",
              "sethdseed",
              "setlabel",
              "setmocktime",
              "setnetworkactive",
              "settxfee",
              "setwalletflag",
              "signmessage",
              "signrawtransactionwithkey",
              "signrawtransactionwithwallet",
              "signmessagewithprivkey",
              "simulaterawtransaction",
              "stop",
              "submitblock",
              "submitheader",
              "submitpackage",
              "syncwithvalidationinterfacequeue",
              "testmempoolaccept",
              "unloadwallet",
              "upgradewallet",
              "uptime",
              "utxoupdatepsbt",
              "validateaddress",
              "verifychain",
              "verifymessage",
              "verifytxoutproof",
              "waitforblock",
              "waitforblockheight",
              "waitfornewblock",
              "walletcreatefundedpsbt",
              "walletlock",
              "walletpassphrase",
              "walletpassphrasechange",
              "walletprocesspsbt",
            ],
          },
          "default": [
            "abandontransaction",
            "abortrescan",
            "addconnection",
            "addmultisigaddress",
            "addnode",
            "addpeeraddress",
            "analyzepsbt",
            "backupwallet",
            "bumpfee",
            "clearbanned",
            "combinepsbt",
            "combinerawtransaction",
            "converttopsbt",
            "createmultisig",
            "createpsbt",
            "createrawtransaction",
            "createwallet",
            "decodepsbt",
            "decoderawtransaction",
            "decodescript",
            "deriveaddresses",
            "disconnectnode",
            "dumptxoutset",
            "dumpwallet",
            "echo",
            "echoipc",
            "echojson",
            "encryptwallet",
            "estimaterawfee",
            "estimatesmartfee",
            "finalizepsbt",
            "fundrawtransaction",
            "generate",
            "generateblock",
            "generatetoaddress",
            "generatetodescriptor",
            "getaddednodeinfo",
            "getaddressesbylabel",
            "getaddressinfo",
            "getbalance",
            "getbalances",
            "getbestblockhash",
            "getblock",
            "getblockchaininfo",
            "getblockcount",
            "getblockfilter",
            "getblockhash",
            "getblockheader",
            "getblockfrompeer",
            "getblockstats",
            "getblocktemplate",
            "getchaintips",
            "getchaintxstats",
            "getconnectioncount",
            "getdeploymentinfo",
            "getdescriptorinfo",
            "getdifficulty",
            "getindexinfo",
            "getinfo",
            "getmemoryinfo",
            "getmempoolancestors",
            "getmempooldescendants",
            "getmempoolentry",
            "getmempoolinfo",
            "getmininginfo",
            "getnettotals",
            "getnetworkhashps",
            "getnetworkinfo",
            "getnewaddress",
            "getnodeaddresses",
            "getpeerinfo",
            "getrawchangeaddress",
            "getrawmempool",
            "getrawtransaction",
            "getreceivedbyaddress",
            "getreceivedbylabel",
            "getrpcinfo",
            "gettransaction",
            "gettxout",
            "gettxoutproof",
            "gettxoutsetinfo",
            "gettxspendingprevout",
            "getunconfirmedbalance",
            "getwalletinfo",
            "getzmqnotifications",
            "help",
            "importaddress",
            "importdescriptors",
            "importmulti",
            "importprivkey",
            "importprunedfunds",
            "importpubkey",
            "importwallet",
            "invalidateblock",
            "joinpsbts",
            "keypoolrefill",
            "listaddressgroupings",
            "listbanned",
            "listlabels",
            "listlockunspent",
            "listreceivedbyaddress",
            "listreceivedbylabel",
            "listsinceblock",
            "listtransactions",
            "listunspent",
            "listwalletdir",
            "listwallets",
            "loadwallet",
            "lockunspent",
            "logging",
            "mockscheduler",
            "ping",
            "preciousblock",
            "prioritisetransaction",
            "pruneblockchain",
            "psbtbumpfee",
            "reconsiderblock",
            "removeprunedfunds",
            "rescanblockchain",
            "savemempool",
            "scantxoutset",
            "send",
            "sendall",
            "sendmany",
            "sendrawtransaction",
            "sendtoaddress",
            "setban",
            "sethdseed",
            "setlabel",
            "setmocktime",
            "setnetworkactive",
            "settxfee",
            "setwalletflag",
            "signmessage",
            "signrawtransactionwithkey",
            "signrawtransactionwithwallet",
            "signmessagewithprivkey",
            "simulaterawtransaction",
            "submitblock",
            "submitheader",
            "submitpackage",
            "syncwithvalidationinterfacequeue",
            "testmempoolaccept",
            "unloadwallet",
            "upgradewallet",
            "uptime",
            "utxoupdatepsbt",
            "validateaddress",
            "verifychain",
            "verifymessage",
            "verifytxoutproof",
            "waitforblock",
            "waitforblockheight",
            "waitfornewblock",
            "walletcreatefundedpsbt",
            "walletlock",
            "walletpassphrase",
            "walletpassphrasechange",
            "walletprocesspsbt",
          ],
        },
        "fetch-blocks": {
          "type": "boolean",
          "name": "Fetch Blocks",
          "description": "Fetch blocks from the network if pruned from disk",
          "default": true,
        },
      },
    },
    "default": [],
  },
  "advanced": {
    "type": "object",
    "name": "Advanced",
    "description": "Advanced settings for Bitcoin Proxy",
    "spec": {
      "tor-only": {
        "type": "boolean",
        "name": "Only Tor Peers",
        "description": "Use Tor for all peer connections",
        "default": false,
      },
      "peer-timeout": {
        "type": "number",
        "name": "Peer Message Timeout",
        "description":
          "How long to wait for a response from a peer before failing",
        "nullable": false,
        "integral": true,
        "units": "Seconds",
        "range": "[0, *)",
        "default": 30,
      },
      "max-peer-age": {
        "type": "number",
        "name": "Maximum Peer Age",
        "description": "How long to wait before refreshing the peer list",
        "nullable": false,
        "integral": true,
        "units": "Seconds",
        "range": "[0, *)",
        "default": 300,
      },
      "max-peer-concurrency": {
        "type": "number",
        "name": "Maximum Peer Concurrency",
        "description":
          "How many peers to reach out to concurrently for block data",
        "nullable": true,
        "integral": true,
        "range": "[1, *)",
        "default": 1,
      },
      "log-level": {
        "type": "enum",
        "name": "Log Level",
        "values": [
          "CRITICAL",
          "ERROR",
          "WARN",
          "INFO",
          "DEBUG",
          "TRACE",
        ],
        "value-names": {
          "CRITICAL": "Critical",
          "ERROR": "Error",
          "WARN": "Warning",
          "INFO": "Info",
          "DEBUG": "Debug",
          "TRACE": "Trace",
        },
        "default": "DEBUG",
      },
    },
  },
});
